onlineshop/onlineshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from shop import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^shoppingcart/', include('shoppingcart.urls')),
    url(r'^base/', views.base),
    url(r'^placeorder/', include('placeorder.urls')),
    url(r'^', include('shop.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

onlineshop/shop/urls.py
from django.conf.urls import url
from shop import views

urlpatterns = [
	url(r'^$', views.product_list, name = "product_list"),
	url(r'^(?P<catSlug>[-\w]+)/$', views.product_list, name = "product_list_by_category"),
	url(r'^(?P<id>\d+)/(?P<prodSlug>[-\w]+)/$', views.product_detail, name = "product_detail"),
]

onlineshop/shoppingcart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
	url(r'^$', views.shoppingcart_list, name="shoppingcart_list"),
	url(r'^list/$', views.shoppingcart_list, name="shoppingcart_list"),
	url(r'^add/(?P<product_id>\d+)/$', views.shoppingcart_add, name = "shoppingcart_add"),
	url(r'^remove/(?P<product_id>\d+)/$', views.shoppingcart_remove, name = "shoppingcart_remove"),
	]

onlineshop/shoppingcart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

onlineshop/shoppingcart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
	"""
		clase que representa el formulario para meter productos en la cesta
		Author: Javier Gomez
	"""
	update = forms.BooleanField(widget=forms.HiddenInput(), initial=False, required=False)
	units = forms.IntegerField(min_value=1,required=True)

onlineshop/shoppingcart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect
from shoppingcart import ShoppingCart
from forms import CartAddProductForm
from shop.models import Product

# Create your views here.
def shoppingcart_list(request):
	"""
	Vista para el fichero list.html que muestra los contenidos el carrito de la compra
	Author: Carlos Li
	"""
	form = CartAddProductForm()
	_shoppingcart = ShoppingCart(request)
	return render(request,'shoppingcart/list.html',
		{'shoppingcart': _shoppingcart,
		'form' : form})

def shoppingcart_add(request,product_id):
	"""
	vista para procesar un formulario para meter un producto en el carrito de la compra
	Author: Javier Gomez
	"""
	try:
		product = Product.objects.get(id=product_id)
	except ObjectDoesNotExist:
		return redirect('product_list')

	shoppingcart=ShoppingCart(request)
	form = CartAddProductForm()
	if request.method == 'POST':
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			units = form.cleaned_data['units']
			update = form.cleaned_data['update']
		else: 
			return redirect('product_list')
	else:
		return redirect('product_list')

	try:
		shoppingcart.addProduct(product=product,
			units=units,
			update_units=update)
	except:
		return render(request, "shop/error.html", {'error' : "not enough stock left for:", 'products' : [product], 'category': None})
		
	return redirect('shoppingcart_list')

def shoppingcart_remove(request,product_id):
	"""
	Vista para procesar un formulario para eliminar un producto del carrito de la compra
	Author: Carlos Li
	"""
	try:
		product = Product.objects.get(id=int(product_id))
	except ObjectDoesNotExist:
		return redirect('product_list')
	shoppingcart=ShoppingCart(request)
	shoppingcart.removeProduct(product)

	return redirect('shoppingcart_list')	

onlineshop/templates/shoppingcart/list.html
{% extends 'shop/base.html' %}


{% block title %}
  {% if category %}
    {{ category.catName }}
  {% else %}
    Products
  {% endif %}
{% endblock %}


{% block header %}
  THE BEST AND MOST AFFORDABLE PARFUMS YOU'LL EVER FIND!
{% endblock %}


{% block content %}
<table class="table">
  <thead class="table-meta">
    <tr>
      <th>Image</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Remove</th>
      <th>Unit price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for prod in shoppingcart %}
      <tr class="table-data">
        <td>
          <a href="/{{ prod.product.id }}/{{ prod.product.prodSlug }}/">
            <img src="{{ prod.product.image.url }}" class="little-image"/>
          </a>
        </td>
        <td>
          <a href="/{{ prod.product.id }}/{{ prod.product.prodSlug }}/">{{ prod.product.prodName }}</a>
        </td>
        <td>
          <p>{{ prod.units }}</p>
          <form action="/shoppingcart/add/{{ prod.product.id }}/" method="post">
            <input type="hidden" name="update" value="True" id="id_update" />
            {% csrf_token %}
            {% for field in form.visible_fields %}
              {{ field.errors }}
              {{ field.help_text }}
              {{ field }}<br>
            {% endfor %}
          <input class="button" type="hidden" name="update" value="True" id="id_update" />
          <input class="button" type="submit" name="submit" value="update quantity">
          <!-- <input type='hidden' name='csrfmiddlewaretoken' value='nTR3XIuHZYmUQvJs3csm4DacgZjY7zvuB12nKUK9mVJ4Wu4m2b9sLuiMVIJxspKg' />  WTF??? -->
          </form>
        </td>
        <td><a class="button" href="/shoppingcart/remove/{{ prod.product.id }}/">Remove<a></td>
        <td class="num">&euro;{{ prod.price  }}</td>
        <td class="num">&euro;{{ prod.total_price  }}</td>
      </tr>
    {% endfor %}
      <tr class="table-meta">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">&euro;{{ shoppingcart.get_total_price }}</td>
      </tr>
  </tbody>
</table>
<p class="text-right">
    <a class="button" href="/" class="button light">Continue shopping</a>
    
    <a class="button" href="/placeorder/create_order/" class="button">Checkout</a>

</p>
{% endblock %}